name: flutter_second_home_task
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3 
  flutter_svg: ^2.0.16
  flutter_sliding_up_panel: ^2.1.1
  intl: ^0.20.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/nav_bar_icon_first.svg
  - assets/nav_bar_icon_second.svg
  - assets/nav_bar_icon_three.svg
  - assets/bottom_navigation_info.svg
